---
## common tasks
- include: 01-hosts_file.yml

## database tasks
- include: 02-create_databases.yml
  when: inventory_hostname in groups['dbs']

## application tasks
- include: 03-app_dir.yml
  when: inventory_hostname in groups['apps']
- include: 04-install_wp.yml
  when: inventory_hostname in groups['apps']
- include: 05-nginx_vhost.yml
  when: inventory_hostname in groups['apps']

## load balancers tasks
- include: 06-add_haproxy.yml
  when: inventory_hostname in groups['lbs']
